Tutorial
salt26/gravita-maze pull request #17
Opened 2022-08-14 17:23 UTC by silee1103

정석대로 풀면 6번째 마지막 빼고는 일단 잘 되지만 거기서 벗어난 짓(자살이라든지...)들을 다 하면 이상하게 꼬입니다...
이런 것들 고칠 때 shutter도 문제 생기면 그거랑 같이 고려하면서 고치고 싶은데 shutter update 내용을 아직 안 받아서 오류가 뜨더라구요...!ㅠㅠ

그래서 main 받아서 하려고 하는데 1000% 충돌이 날 것 같아서 그 전에 branch에 다 올려 놓고 pr 부탁드리게 되었습니다...!!ㅠㅠ

2022-08-14 18:15 UTC, salt26 commented
일단 이거 반영 안 하고 v1.3.1 릴리즈한 다음에, 아침에 리뷰할게요!

2022-08-15 02:54 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 1, 1), "Shutter also can.");
여기 부분 문장이 완성이 안 된 것 같네!

2022-08-15 03:01 UTC, salt26 requested changes
적어둔 코멘트들 보고 변경해서 올려주면 좋겠어!

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        if (mm == null || mm.currentMovableCoord[posX, posY] is Ball){
여기 조건은 `mm != null && mm.currentMovableCoord[posX, posY] is Ball` 이 되어야 해!  
mm이 없을 때 `IsBallThere()`가 true를 반환하는 건 좀 이상하잖아.

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>      {
메서드명(함수명)은 첫 글자가 대문자로 시작해야 해!

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>      {
메서드명(함수명)은 첫 글자가 대문자로 시작해야 해!

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        if (mm == null||mm.currentMovableCoord[posX, posY] is Iron){
여기도 82줄처럼 조건이 바뀌어야겠지?

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>      public void showText(string text){
메서드명(함수명)은 첫 글자가 대문자로 시작해야 해!

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +    public void hideText(TutorialGuideUI currentTip){
메서드명(함수명)은 첫 글자가 대문자로 시작해야 해!

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +                emergencyText = "Your Ball Escape! Congratulation!";
"Your ball escaped! Congratulation!"으로 적는 게 좋을 것 같아!

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 1, 1), "Shutter also can.");
여기 부분 문장이 완성이 안 된 것 같아...

2022-08-15 03:01 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(4, 2, 0), "A heavy Iron can crush a ball...");
문장 안에서 `Iron`은 `iron`으로 바꿔주면 좋겠어! 문장의 첫 글자 빼고는 전부 소문자로.

2022-08-15 07:30 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 1, 1), "Shutter also can.");
이거는 보면서 하려구! 혹시 저게 없어서 안돌아가는 줄 알고 임시로 적어둔 거!ㅠㅠ

2022-08-15 08:07 UTC, salt26 approved these changes
Great! Thanks for your effort!

2022-08-15 08:07 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 1, 1), "Shutter also can.");
문장 표현은 나중에 내가 조금씩 고쳐볼게! 수고했어!

2022-08-15 08:07 UTC, merged