tutorial tip finish
salt26/gravita-maze pull request #18
Opened 2022-08-15 12:25 UTC by silee1103

일단 문제 나는 건 다 고친 것 같아요
근데 사용자가 이상하게 생각하거나 이해가 잘 안 될 수도 있는 부분은 추후에 좀 더 말을 다듬든지 해야 할 것 같습니다.!!

2022-08-15 14:28 UTC, salt26 requested changes
조금만 고쳐주세요!

2022-08-15 14:28 UTC, salt26 commented on Assets/Scenes/Tutorial.unity
> +  - {fileID: 4900000, guid: 92523361af9f3094b891015498ab8441, type: 3}
음? 이거 순서 바꾼 이유가 뭔가요??
Tutorial4 -> Tutorial5 순서가 맞는데...

2022-08-15 14:28 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>      public void retryButtonDown(){
함수(메서드) 이름은 대문자로 해주세요!

2022-08-15 14:44 UTC, salt26 requested changes

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(7, 0, 2), "Press the right arrow to close the shutter if the green wall exists.");
Ball이 (7, 0, 0)으로 이동했을 때에도 안내가 필요할 것 같아요.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +                emergencyText = "Your ball is crushed by the box!\nPress the shiny retry button to try again.";
`the box` -> `the iron`으로 고쳐주세요!

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 4, 0), "Of course, sometimes you can be trapped by the shutter, too. Press retry button!");
이건 해당 맵에서 일어날 가능성이 없는 수에요.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(7, 0, 2), "Press the right arrow to close the shutter if the green wall exists.");
64줄의 표현을 "Press the right arrow to close the green shutter."라고 바꿔보죠.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(5, 2, 1), "And also, iron can escape outside!");
`The iron can be removed by escaping outside!"로 표현을 바꿔보죠.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(5, 2, 0), "Now, you can just escape with iron.");
`with the iron.`으로 바꿔봅시다.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(5, 2, 1), "And also, iron can escape outside!");
56줄, 57줄, 59줄, 60줄을 이렇게 바꿔주세요.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(2, 1, 2), "We're almost there...");
여기 51줄에 해당하는 내용은 아닌데, 54줄의 `your ball`이라는 표현을 `the ball`라고 바꿔봅시다.

2022-08-15 14:44 UTC, salt26 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 4, 0), "Of course, sometimes you can be trapped by the shutter, too. Press retry button!");
대신에 8번 맵의 적당한 위치(처음 제외)에서 "The iron cannot activate the shutter. Only the ball can activate the shutter."라는 메시지를 출력해주면 좋겠어요.

2022-08-16 03:58 UTC, silee1103 commented on Assets/Scenes/Tutorial.unity
> +  - {fileID: 4900000, guid: 92523361af9f3094b891015498ab8441, type: 3}
음....? 왠지 제 컴에서는 자꾸 5->4로 나와서 계속 그것부터 체크하고 바꿔야 하더라구요!!
오빠 컴에서는 4->5인게 내 컴에서는 5->4로 되어있어.... 왜지???

2022-08-16 03:59 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
>      public void retryButtonDown(){
아앗 맞다;; 죄송합니다

2022-08-16 04:13 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(5, 2, 0), "Now, you can just escape with iron.");
수행했습니다!

2022-08-16 04:13 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(2, 1, 2), "We're almost there...");
수행했습니다!

2022-08-16 04:13 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
>          tipDict.Add(new TutorialTuple(5, 2, 1), "And also, iron can escape outside!");
수행했습니다!

2022-08-16 04:13 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(8, 4, 0), "Of course, sometimes you can be trapped by the shutter, too. Press retry button!");
아래 코멘트 수행했습니다!

2022-08-16 04:13 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
> +                emergencyText = "Your ball is crushed by the box!\nPress the shiny retry button to try again.";
수행했습니다!

2022-08-16 04:13 UTC, silee1103 commented on Assets/Scripts/TutorialGuide.cs
> +        tipDict.Add(new TutorialTuple(7, 0, 2), "Press the right arrow to close the shutter if the green wall exists.");
수행했습니다!

2022-08-16 09:23 UTC, salt26 commented on Assets/Scenes/Tutorial.unity
> +  - {fileID: 4900000, guid: 92523361af9f3094b891015498ab8441, type: 3}
??? 왜일까? ㅋㅋㅋㅋ

2022-08-16 09:25 UTC, salt26 approved these changes
좋아요!

2022-08-16 09:26 UTC, merged